"use client";

import React from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { ArrowRight, X } from "lucide-react";

interface StepBasicInfoProps {
  name: string;
  setName: (v: string) => void;
  slug: string;
  setSlug: (v: string) => void;
  excerpt: string;
  setExcerpt: (v: string) => void;
  description: string;
  setDescription: (v: string) => void;
  onNext: () => void;
  onCancel: () => void;
}

export function StepBasicInfo({
  name,
  setName,
  slug,
  setSlug,
  excerpt,
  setExcerpt,
  description,
  setDescription,
  onNext,
  onCancel,
}: StepBasicInfoProps) {
  const [isSlugManual, setIsSlugManual] = React.useState(false);
  const [errors, setErrors] = React.useState<Record<string, string>>({});
  const [touched, setTouched] = React.useState<Record<string, boolean>>({});

  // Helper to generate slug
  const formatSlug = (text: string) => {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "") // Remove non-alphanumeric
      .replace(/\s+/g, "-")         // Spaces to hyphens
      .replace(/-+/g, "-")          // Collapse multiple hyphens
      .trim();
  };

  const handleNameChange = (val: string) => {
    setName(val);
    if (!isSlugManual) {
      setSlug(formatSlug(val));
    }
  };

  const handleSlugChange = (val: string) => {
    setIsSlugManual(true);
    setSlug(val.toLowerCase().replace(/\s+/g, "-"));
  };

  // Validation
  React.useEffect(() => {
    const newErrors: Record<string, string> = {};
    if (touched.name && name.trim().length < 2) {
      newErrors.name = "Product name must be at least 2 characters.";
    }
    if (touched.slug) {
      if (!slug.trim()) {
        newErrors.slug = "Product slug is required.";
      } else if (!/^[a-z0-9-]+$/.test(slug)) {
        newErrors.slug = "Slug must contain only lowercase letters, numbers, and hyphens.";
      }
    }
    if (touched.excerpt && excerpt.trim().length < 10) {
      newErrors.excerpt = "Excerpt must be at least 10 characters.";
    }
    if (touched.description && description.trim().length < 20) {
      newErrors.description = "Description must be at least 20 characters.";
    }
    setErrors(newErrors);
  }, [name, slug, excerpt, description, touched]);

  const handleBlur = (field: string) => {
    setTouched((prev) => ({ ...prev, [field]: true }));
  };

  const isFormValid =
    name.trim().length >= 2 &&
    slug.trim().length >= 1 &&
    /^[a-z0-9-]+$/.test(slug) &&
    excerpt.trim().length >= 10 &&
    description.trim().length >= 20;

  const handleSubmitNext = (e: React.FormEvent) => {
    e.preventDefault();
    // Touch all fields to trigger any validation before going next
    setTouched({
      name: true,
      slug: true,
      excerpt: true,
      description: true,
    });

    if (isFormValid) {
      onNext();
    }
  };

  return (
    <form onSubmit={handleSubmitNext} className="space-y-6">
      <div className="space-y-4">
        {/* Name Input */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-foreground">Product Name *</label>
          <Input
            value={name}
            onChange={(e) => handleNameChange(e.target.value)}
            onBlur={() => handleBlur("name")}
            placeholder="e.g. Classic Gold Ring"
            className={errors.name ? "border-destructive focus-visible:ring-destructive bg-background" : "bg-background border-input"}
            required
          />
          {errors.name && <p className="text-xs text-destructive font-medium">{errors.name}</p>}
        </div>

        {/* Slug Input */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-foreground">URL Slug *</label>
          <Input
            value={slug}
            onChange={(e) => handleSlugChange(e.target.value)}
            onBlur={() => handleBlur("slug")}
            placeholder="e.g. classic-gold-ring"
            className={errors.slug ? "border-destructive focus-visible:ring-destructive font-mono bg-background" : "bg-background border-input font-mono"}
            required
          />
          <p className="text-[11px] text-muted-foreground">
            Autogenerated from title. Lowercase letters, numbers, and hyphens only.
          </p>
          {errors.slug && <p className="text-xs text-destructive font-medium">{errors.slug}</p>}
        </div>

        {/* Excerpt Input */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-foreground">Short Excerpt *</label>
          <Input
            value={excerpt}
            onChange={(e) => setExcerpt(e.target.value)}
            onBlur={() => handleBlur("excerpt")}
            placeholder="Brief summary of the product for listings (min 10 chars)..."
            className={errors.excerpt ? "border-destructive focus-visible:ring-destructive bg-background" : "bg-background border-input"}
            required
          />
          {errors.excerpt && <p className="text-xs text-destructive font-medium">{errors.excerpt}</p>}
        </div>

        {/* Description Input */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-foreground">Detailed Description *</label>
          <Textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            onBlur={() => handleBlur("description")}
            placeholder="Provide a rich and detailed description of materials, style, craftsmanship (min 20 chars)..."
            className={errors.description ? "border-destructive focus-visible:ring-destructive min-h-[120px] bg-background" : "bg-background border-input min-h-[120px]"}
            required
          />
          {errors.description && <p className="text-xs text-destructive font-medium">{errors.description}</p>}
        </div>
      </div>

      {/* Button Controls */}
      <div className="flex items-center justify-between border-t border-border/60 pt-4">
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
          className="gap-2 border-border text-muted-foreground hover:bg-accent hover:text-foreground rounded-lg"
        >
          <X className="h-4 w-4" /> Cancel
        </Button>
        <Button
          type="submit"
          disabled={!isFormValid}
          className="gap-2 shadow-sm rounded-lg"
        >
          Next Step <ArrowRight className="h-4 w-4" />
        </Button>
      </div>
    </form>
  );
}
